### ISSUE TITLE
Youtube-dl downloaded files are not removed

### ISSUE THREAD

**Issue by StealthyLoner** [tietokilta-saato/tikplay#5]
The youtube retriever downloads the song to `self.conf["download_dir"]` and then converts that song to `self.conf["download_dir"]/yt/` but doesnt remove the `mp4` file it downloaded leaving duplicate files to the disk.

**Comment by shadikka** [comment]
Fixed in https://github.com/tietokilta-saato/tikplay/commit/89b364fd42929e1f49115687549c8fba558feb8f
