### ISSUE TITLE
Generic retriever just dumps the file with "invalid" filename to disk

### ISSUE THREAD

**Issue by StealthyLoner** [tietokilta-saato/tikplay#6]
The retriever fails to do any "parsing" or "logic" to the file it downloads, resulting `Genericurl-<url>` files staying on disk and failing to play (Apparently the other logic doesn't find the song since it is named wrong)

**Comment by shadikka** [comment]
Fixed in https://github.com/tietokilta-saato/tikplay/commit/89b364fd42929e1f49115687549c8fba558feb8f

**Comment by shadikka** [comment]
Fixed by `ln -s /usr/bin/avprobe /usr/bin/ffprobe`. Debian...

Also kind of fixed by https://github.com/tietokilta-saato/tikplay/commit/09ae5d3fc4f164bf18516e8ddfd362513a53ad86 by actually logging the specific error.
