### ISSUE TITLE
Skip causes Internal Server Error

### ISSUE THREAD

**Issue by hanzki** [tietokilta-saato/tikplay#7]
The skip command seems to work but it always returns 500 response. This seems to happen with the offical client at kekkonen and with my own client.

**Comment by StealthyLoner** [comment]
Is this an issue with the tikplay-client python module or this server. I couldn't reproduce this issue with:
`curl -X DELETE localhost:5000/srv/v1.0/song`

**Comment by StealthyLoner** [comment]
I managed to replicate the issue. This happens whenever `len(playlist) <= 1`
