### ISSUE TITLE
Clear requests always return empty response

### ISSUE THREAD

**Issue by hanzki** [tietokilta-saato/tikplay#8]
The clear requests seem to work as they should but the server response is always { "text": null } which is very unhelpful. It could respond for example with the number of songs cleared. Or at least OK instead of null.

**Comment by StealthyLoner** [comment]
Can you provide an example of one such request

**Comment by StealthyLoner** [comment]
https://github.com/tietokilta-saato/tikplay/commit/83d777e11e003f70aa5cd051cd43b063036b47db fixes the issue! Now it returns {'text': True}
